### ISSUE TITLE
Javascript error if location is not set

### ISSUE THREAD

**Issue by espenmn** [Socrapop/travelers-map#14]
If I add a location short code to a content type (post) that does not have the a location, I get a (javascript) error. 

Maybe a check for lat/lng would work ?

**Comment by Socrapop** [comment]
If I understand well, you are trying to load a map that does not have any marker on it?
Usually, you get a map with a message "LeafletJS is loading..." and maybe an error yes.

I already planned to change the message when this is the case, I will also remove the errors in the console. I will not load the map without any marker because that's not this plugin's purpose. I prefer to show an error so the unexperimented users see why their map is not showing.

Did I understand what you wanted? If not, could you precisely tell me where you see the error, what error is it, and how to reproduce?

**Comment by espenmn** [comment]
If did a bit of testing, and this is a workaround (no idea if it is a good way to do it):

**if ($cttm_postdatas) {**
      //Send Json variables to our javascript file 'travelersmap.js'
      wp_localize_script('travelersmap_init', 'cttm_options_params', $cttm_options_params);
      wp_localize_script('travelersmap_init', 'cttm_shortcode_' . $id, ${"cttm_shortcode_$id"});

      $cttm_output =   '<div id="' . $containerid . '" class="travelersmap-container" style="z-index: 1; min-height: 10px; min-width:10px; height:' . $height . ';width:' . $width . '; max-width:' . $maxwidth . '; max-height:' . $maxheight . '; "><div style="position:absolute; z-index:-1;top: 50%;text-align: center;display: block;left: 50%;transform: translate(-50%,-50%);">Travelers\' Map is loading... <br> If you see this after your page is loaded completely, leafletJS files are missing.</div></div>';

      return $cttm_output;
    **}**
