### ISSUE TITLE
The ability to display not all marks on the map

### ISSUE THREAD

**Issue by Olegggggggg** [Socrapop/travelers-map#5]
Hello. I tried your card and I really liked it, but I miss one detail. We can say that on my page there are three main elements: filter, listings, map. If I use the filter and some of the listings are hidden, they will still be displayed on the map. It would be cool if you can make sure that entries that do not appear on the page do not appear on the map.
I hope you understand what I mean, because I write through Google Translate)
Thank)

**Comment by Socrapop** [comment]
Dear Olegggggggg,

The only way to filter posts in this plugin is to use shortcode, and it's not linked to your actual loop. Furthermore, it would need to be developed very specifically for your filters, and would be difficult to adapt to every WordPress website.

However,  I plan to implement a filtering system directly above the map with user filters, but since it's a major feature that need a lot of thinking, I will do it in a long time, maybe in version 2.0 of the plugin.
